<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ShellDocs.Core\ShellDocs.Core.csproj" />
    <ProjectReference Include="..\..\src\ShellDocs.Markdown\ShellDocs.Markdown.csproj" />
    <ProjectReference Include="..\..\src\ShellDocs.Components\ShellDocs.Components.csproj" />
    <ProjectReference Include="..\..\src\ShellDocs.Templates\ShellDocs.Templates.csproj" />
    <ProjectReference Include="..\..\src\ShellDocs.Tokens\ShellDocs.Tokens.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

</Project>
